[package]
name = "project-euler-rust"
version = "0.1.0"
authors = ["NoahStolk <noah.stolk@gmail.com>"]
edition = "2018" # supported edition

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
